### ISSUE TITLE
Avaliação do Projeto

### ISSUE THREAD

**Issue by quindai** [mpinheirodev/ProjetoFloresta#1]
- [ OK ] Encapsulamento
- [ OK ] Herança
- [ ] Polimorfismo
- [ OK ] Associação
- [ OK ] Métodos e Comportamentos
- [ OK ] Construtores e Instanciação
- [ OK ] Gerenciamento do Ecossistema
- [  ] Gerenciamento do Projeto
- [ OK ] Nome e Matrícula no README

Poderia ter usado enum nas espécies dos animais.
Não houve uso explícito de Polimorfismo.
Nota do Projeto 8.
Se quiser melhorar a nota na AV2, implemente polimorfismo.
AV2 é a mesma nota do projeto.

**Comment by mpinheirodev** [comment]
Modificações adicionadas à branch Development.
